---
title: '2022'
author: "Parker Bausman"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
```

#This file will be utilizing chunks from the 2023 pipeline to process the 2022 data.

```{r}
#float 1 has interspersed 2023 and 2022, select 2022 

Float2022.1 <- Float1[grepl("2022", Float1$Date, fixed = TRUE), ]
Float2022.2 <- Float2[grepl("2022", Float2$Date, fixed = TRUE), ]

# Convert to data frames if they are not already
Float2022.1 <- as.data.frame(Float2022.1)
Float2022.2 <- as.data.frame(Float2022.2)
```


```{r}
#make sure rows are the same so that rbind can work to combine datasets 
Float2022.1 <- Float2022.1[ ,c(1:3, 9, 12)]
Float2022.2 <- Float2022.2[ ,c(1:3, 9, 12)]
```

```{r}
#Rename Col ID on float1.2
Float2022.1 <- Float2022.1 %>%
  rename(ID = X.2)
```

```{r}
#Float 2022.1 needs to have ponds renamed to just number not MC POND X
```


```{r}
#combine data 
Float2022 <- rbind(Float2022.1,Float2022.2)
```

```{r}
#to add average lenghts I need to make a new column
Float2022$Length <- NA
```

```{r}
# ugly for loop to attach lengths (changed from micro to millimeter )
#these are the average lengths of bugs, some of which have been updated from 2022 measures. Some like the dipt have not been readjusted yet as I doubt there will be much change. Will check soon. Also adds externus 
#curious to look into the high size variability within asynarchus 
#nemo seem a lot smaller in 2022, I should measure every single nemo captured and run a ttest 
#need to measure zygoptera 
#midge values seem wrong... 
for (i in 1:nrow(Float2022)) {
  # Check which pond 
  if (Float2022$ID[i] == "Antisoptera") {
    # If ID is antisoptera, add length
    #units is mm
    Float2022$Length [i] <- 59.000
    #measure more dragonflies
  } else if (Float2022$ID[i] == "nigriculus") {
    # etc..
    Float2022$Length [i] <- 14.1212222222222
    
  } else if (Float2022$ID[i] == "hostilis") {
    # etc..
    Float2022$Length [i] <- 17.74
    
  } else if (Float2022$ID[i] == "Zygoptera") {
    # etc..
    Float2022$Length [i] <- 33
    
  } else if (Float2022$ID[i] == "Midges") {
    # etc..
    Float2022$Length [i] <- 3.45853
    
  } else if (Float2022$ID[i] == "Ceratopogonidae") {
    # etc..
    Float2022$Length [i] <- 2.131
    
  } else if (Float2022$ID[i] == "Diptera") {
    # etc..
    Float2022$Length [i] <- 3.000
    
  } else if (Float2022$ID[i] == "externus") {
    # etc..
    Float2022$Length [i] <- 14.13
    
  } else if (Float2022$ID[i] == "Mosquito") {
    # etc..
    Float2022$Length [i] <- 5.8935
    
  }
}
```


```{r}
subsetFloat2022 <- subset(Float2022, ID %in% c("Antisoptera","nigriculus", "hostilis", "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera", "externus"))
```

#now the LW-Dry-Mass 


```{r}
#read in LW data 
lw<-read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/LW-Float.csv",header=TRUE)
head(lw)
```



```{r}
#merge float data and LW data 
merge <- merge(subsetFloat2022, lw, by="ID", all=T)
EMERGE2022 <- merge
```

```{r}
# calculating log (dry weight) from length
EMERGE2022$logDW <- with(EMERGE2022, a + (b * log((Length), base=base)))

#untransforming log (dry weight) to dry weight (mg)
EMERGE2022$DW <- with(EMERGE2022, (base^(logDW)))
```

```{r}
#now multiply dry weight by number of individuals 
EMERGE2022$SampleDW <- NA

EMERGE2022$SampleDW <- (EMERGE2022$DW * EMERGE2022$Count)
```

```{r}
EMERGE2022$Date <- as.Date(EMERGE2022$Date, format = "%d-%b-%Y")
```

```{r}
#pull out nemo
NemoDW2022 <- subset(EMERGE2022, ID %in% c("hostilis"))
TotalNemo2022 <- sum(NemoDW$SampleDW)
TotalNemo
```

```{r}
DW2022 <- subset(EMERGE2022, ID %in% c("Antisoptera","nigriculus", "hostilis", "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera", "externus"))
DryWeight2022 <- sum(DW2022$SampleDW)
DryWeight2022

# Dragonflies are over represented mass wise 
```

```{r}
#create a df with just nemo 
nemoDW22 <- subset(EMERGE2022, ID %in% c( "hostilis"))
#aggregate by date 
NemoDate2022<- aggregate(nemoDW22$SampleDW ~ nemoDW22$Date, data = nemoDW22, FUN= sum)
NemoDate2023<- aggregate(NemoDW$SampleDW ~ NemoDW$Date, data = NemoDW, FUN= sum)

```


```{r}
NoNemoDW2022 <- subset(EMERGE2022, ID %in% c("Antisoptera","nigriculus",  "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera", "externus"))


NoNemoDate2022<- aggregate(NoNemoDW2022$SampleDW ~ NoNemoDW2022$Date, data = NoNemoDW2022, FUN= sum)

```

```{r}
NemoDWM2 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/Nemo-22-23-dwm2.csv" , header = TRUE)

NemoDWM2$Date <- as.Date(NemoDWM2$Date, format = "%d-%b")

```

```{r}
ggplot(NemoDWM2, aes(x = Date)) +
  geom_point(aes(y = NemoM2022, color = "NemoM2022"), size = 2) +
  geom_point(aes(y = NemoM2023, color = "NemoM2023"), size = 2) +
  geom_line(aes(y = NemoM2022, color = "NemoM2022"), size = .5) +
  geom_line(aes(y = NemoM2023, color = "NemoM2023"), size = .5) +
  labs(x = "Date", y = "Nemo Emergence mg/m2", color = "Year") +
  scale_color_manual(values = c("NemoM2022" = "blue", "NemoM2023" = "red"),
                     labels = c("NemoM2022" = "2022", "NemoM2023" = "2023")) +
  theme_minimal()

```



```{r}
AllOtherDW <- subset(EMERGE2022, )
```

```{r}
#create a df of all other DW without nemo 
NoNemoDry23 <- AllOtherDW
NoNemoDry23 <- subset(NoNemoDry23, !grepl("hostilis", ID))

NoNemoDry22 <- DW2022
NoNemoDry22 <- subset(NoNemoDry22, !grepl("hostilis", ID))

```

```{r}
#mg per sample date sans nemo 
OtherDWDate22 <- aggregate(NoNemoDry22$SampleDW ~ NoNemoDry22$Date, data = NoNemoDry22, FUN= sum)
OtherDWDate23 <- aggregate(NoNemoDry23$SampleDW ~ NoNemoDry23$Date, data = NoNemoDry23, FUN= sum)

```



```{r}
#find the sum of dw per date (sans nemo)
dwDate22 <- aggregate(NoNemoDry22$SampleDW ~ NoNemoDry22$Date, data = NoNemoDry22, FUN= sum)

```

```{r}
#this is nemo and other bugs emergence per day mg/m2
othervsnemo22 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/2022-Nemo-Other-m2.csv" , header = TRUE)

othervsnemo2022 <- othervsnemo2022[,c(-4,-5)]

othervsnemo22$Date <- as.Date(othervsnemo22$Date, format = "%d-%b")
```

```{r}
ggplot(othervsnemo22, aes(x = Date)) +
  geom_point(aes(y = NemoM2022, color = "NemoM2022"), size = 2) +
  geom_point(aes(y = OtherDWM22, color = "OtherDWM22"), size = 2) +
  geom_line(aes(y = NemoM2022, color = "NemoM2022"), size = .5) +
  geom_line(aes(y = OtherDWM22, color = "OtherDWM22"), size = .5) +
  labs(x = "Date", y = " Emergence mg/m2", color = "Type") +
  scale_color_manual(values = c("NemoM2022" = "blue", "OtherDWM22" = "red"),
                     labels = c("NemoM2022" = "Nemo 2022", "OtherDWM22" = "Other Bugs 2022")) +
  theme_minimal()

```



```{r}
# Filter out NA values from the columns you are plotting
othervsnemo22_filtered <- othervsnemo22[complete.cases(othervsnemo22$NemoM2023), ]
othervsnemo22_filtered <- othervsnemo22_filtered[complete.cases(othervsnemo22_filtered$OtherDWM23), ]

# Plotting with filtered data
ggplot(othervsnemo22_filtered, aes(x = Date)) +
  geom_point(aes(y = NemoM2023, color = "NemoM2023"), size = 2) +
  geom_point(aes(y = OtherDWM23, color = "OtherDWM23"), size = 2) +
  geom_line(aes(y = NemoM2023, color = "NemoM2023"), size = 0.5) +
  geom_line(aes(y = OtherDWM23, color = "OtherDWM23"), size = 0.5) +
  labs(x = "Date", y = "Emergence mg/m2", color = "Type") +
  scale_color_manual(values = c("NemoM2023" = "green", "OtherDWM23" = "orange"),
                     labels = c("NemoM2023" = "Nemo 2023", "OtherDWM23" = "Other Bugs 2023")) +
  theme_minimal()
```



### Now im curious to look at just super source ponds like pond 1 in 2022 

```{r}
Pond1in2022 <- subset(EMERGE2022, ID %in% c("Antisoptera","nigriculus","hostilis", "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera", "externus"))

#pull out pond 1 
Pond1in2022 <- subset(EMERGE2022, Pond %in% c("1", "MC Pond 1"))

#separate pond 1 others
P1Other22 <- subset(Pond1in2022, ID %in% c("Antisoptera","nigriculus", "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera", "externus"))

# pond 1 nemo 
P1Nemo22 <- subset(Pond1in2022, ID %in% c("hostilis"))

#Lump by date 
P1Nemo22Date<- aggregate(P1Nemo22$SampleDW ~ P1Nemo22$Date, data = P1Nemo22, FUN= sum)

P1Other22Date<- aggregate(P1Other22$SampleDW ~ P1Other22$Date, data = P1Other22, FUN= sum)

# now make the spreadsheet 


```

```{r}
pond1stuff <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/Pond1-2022-Emergence.csv" , header = TRUE)

pond1stuff$Date <- as.Date(pond1stuff$Date, format = "%d-%b")
```

```{r}
# Plotting with filtered data
ggplot(pond1stuff, aes(x = Date)) +
  geom_point(aes(y = Pond1NemoM2, color = "Pond1NemoM2"), size = 2) +
  geom_point(aes(y = Pond1OtherM2, color = "Pond1OtherM2"), size = 2) +
  geom_line(aes(y = Pond1NemoM2, color = "Pond1NemoM2"), size = 0.5) +
  geom_line(aes(y = Pond1OtherM2, color = "Pond1OtherM2"), size = 0.5) +
  labs(x = "Date", y = "Emergence mg/m2", color = "Type") +
  scale_color_manual(values = c("Pond1NemoM2" = "green", "Pond1OtherM2" = "orange"),
                     labels = c("Pond1NemoM2" = "Pond1NemoM2 ", "Pond1OtherM2" = "Other Bugs 2023")) +
  theme_minimal()
```

