---
title: "Avg"
author: "Parker Bausman"
date: "2024-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


#plot avgs per date with standard error 
```{r}

AllPonds22 <- subset(floating2022, Pond %in% c("1", "3", "5", "6","12","8","9"))

AllPonds22Nemo <- subset(AllPonds22, ID %in% c("Nemo"))
AllPonds22Other <- subset(AllPonds22, ID %in% c("Other"))


AllPonds22NemoDate <- aggregate(AllPonds22Nemo$Total_SampleDW ~ AllPonds22Nemo$Date, data = AllPonds22Nemo, FUN = mean)


AllPonds22OtherDate <- aggregate(AllPonds22Other$Total_SampleDW ~ AllPonds22Other$Date, data = AllPonds22Other, FUN = mean)

#need to rename col for succesful merge 
names(AllPonds22NemoDate)[names(AllPonds22NemoDate) == 'AllPonds22Nemo$Date'] <- 'Date'
names(AllPonds22OtherDate)[names(AllPonds22OtherDate) == 'AllPonds22Other$Date'] <- 'Date'

AllPondBarChart <- left_join(AllPonds22NemoDate, AllPonds22OtherDate, by = "Date")

names(AllPondBarChart)[names(AllPondBarChart) == 'AllPonds22Nemo$Total_SampleDW'] <- 'NemoDry'

names(AllPondBarChart)[names(AllPondBarChart) == 'AllPonds22Other$Total_SampleDW'] <- 'NoNemoDry'
```

```{r}
# Calculate the mean, standard deviation, and count for each Date
mean_sd_count22Nemo <- aggregate(Total_SampleDW ~ Date, data = AllPonds22Nemo, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Nemo <- do.call(data.frame, mean_sd_count22Nemo)
mean_sd_count22Nemo$mean <- mean_sd_count22Nemo$Total_SampleDW[, "mean"]
mean_sd_count22Nemo$sd <- mean_sd_count22Nemo$Total_SampleDW[, "sd"]
mean_sd_count22Nemo$n <- mean_sd_count22Nemo$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Nemo$se <- mean_sd_count22Nemo$Total_SampleDW.sd / sqrt(mean_sd_count22Nemo$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Nemo)[names(mean_sd_count22Nemo) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Nemo <- mean_sd_count22Nemo[, c("Date", "mean", "se")]
mean_sd_count22Nemo$Type <- "NemoDry"


#GET SE FOR OTHER TOO 
# Calculate the mean, standard deviation, and count for each Date
mean_sd_count22Other <- aggregate(Total_SampleDW ~ Date, data = AllPonds22Other, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Other <- do.call(data.frame, mean_sd_count22Other)
mean_sd_count22Other$mean <- mean_sd_count22Other$Total_SampleDW[, "mean"]
mean_sd_count22Other$sd <- mean_sd_count22Other$Total_SampleDW[, "sd"]
mean_sd_count22Other$n <- mean_sd_count22Other$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Other$se <- mean_sd_count22Other$Total_SampleDW.sd / sqrt(mean_sd_count22Other$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Other)[names(mean_sd_count22Other) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Other <- mean_sd_count22Other[, c("Date", "mean", "se")]
mean_sd_count22Other$Type <- "NoNemoDry"

```

```{r}
SE <- rbind(mean_sd_count22Other, mean_sd_count22Nemo )


AllPondBarChart <- AllPondBarChart %>%
  pivot_longer(cols = c(NoNemoDry, NemoDry),
               names_to = "Type",
               values_to = "Biomass")


AllPondBarChart <- merge(AllPondBarChart, SE)

AllPondBarChart$Date <- as.Date(AllPondBarChart$Date , format = "%d-%b-%y")
AllPondBarChart$Date <- gsub("2022-", "", AllPondBarChart$Date)
```

```{r}
# Assuming your dataset has 'Biomass_SD' for the standard deviation
ggplot(AllPondBarChart, aes(x = `Date`, y = Biomass, fill = Type)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin = Biomass - se, ymax = Biomass + se),
                position = position_dodge(width = 0.9),
                width = 0.25) + # Width of the error bars
  labs(x = "Date 2022", y = "Biomass (mg)", title = "Average subsidy export of 7 sampled ponds in 2022 (1,3,5,6,8,9,12)") +
  scale_fill_manual(values = c("NoNemoDry" = "red", "NemoDry" = "blue"),
                    labels = c("N. hostilis", "Other insects")) +
  ylim(0,500) +
  theme_minimal()

```



```{r}

AllPonds22 <- subset(floating2023, Pond %in% c("1", "3", "5", "6","12","8","9"))

AllPonds22Nemo <- subset(AllPonds22, ID %in% c("Nemo"))
AllPonds22Other <- subset(NoDragon2023, ID %in% c("Other"))


AllPonds22NemoDate <- aggregate(AllPonds22Nemo$Total_SampleDW ~ AllPonds22Nemo$Date, data = AllPonds22Nemo, FUN = mean)


AllPonds22OtherDate <- aggregate(AllPonds22Other$Total_SampleDW ~ AllPonds22Other$Date, data = AllPonds22Other, FUN = mean)

#need to rename col for succesful merge 
names(AllPonds22NemoDate)[names(AllPonds22NemoDate) == 'AllPonds22Nemo$Date'] <- 'Date'
names(AllPonds22OtherDate)[names(AllPonds22OtherDate) == 'AllPonds22Other$Date'] <- 'Date'

AllPondBarChart <- left_join(AllPonds22NemoDate, AllPonds22OtherDate, by = "Date")

names(AllPondBarChart)[names(AllPondBarChart) == 'AllPonds22Nemo$Total_SampleDW'] <- 'NemoDry'

names(AllPondBarChart)[names(AllPondBarChart) == 'AllPonds22Other$Total_SampleDW'] <- 'NoNemoDry'
```

```{r}
# Calculate the mean, standard deviation, and count for each Date
mean_sd_count22Nemo <- aggregate(Total_SampleDW ~ Date, data = AllPonds22Nemo, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Nemo <- do.call(data.frame, mean_sd_count22Nemo)
mean_sd_count22Nemo$mean <- mean_sd_count22Nemo$Total_SampleDW[, "mean"]
mean_sd_count22Nemo$sd <- mean_sd_count22Nemo$Total_SampleDW[, "sd"]
mean_sd_count22Nemo$n <- mean_sd_count22Nemo$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Nemo$se <- mean_sd_count22Nemo$Total_SampleDW.sd / sqrt(mean_sd_count22Nemo$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Nemo)[names(mean_sd_count22Nemo) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Nemo <- mean_sd_count22Nemo[, c("Date", "mean", "se")]
mean_sd_count22Nemo$Type <- "NemoDry"


#GET SE FOR OTHER TOO 
# Calculate the mean, standard deviation, and count for each Date
mean_sd_count22Other <- aggregate(Total_SampleDW ~ Date, data = AllPonds22Other, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Other <- do.call(data.frame, mean_sd_count22Other)
mean_sd_count22Other$mean <- mean_sd_count22Other$Total_SampleDW[, "mean"]
mean_sd_count22Other$sd <- mean_sd_count22Other$Total_SampleDW[, "sd"]
mean_sd_count22Other$n <- mean_sd_count22Other$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Other$se <- mean_sd_count22Other$Total_SampleDW.sd / sqrt(mean_sd_count22Other$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Other)[names(mean_sd_count22Other) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Other <- mean_sd_count22Other[, c("Date", "mean", "se")]
mean_sd_count22Other$Type <- "NoNemoDry"

```

```{r}
SE <- rbind(mean_sd_count22Other, mean_sd_count22Nemo )


AllPondBarChart <- AllPondBarChart %>%
  pivot_longer(cols = c(NoNemoDry, NemoDry),
               names_to = "Type",
               values_to = "Biomass")


AllPondBarChart <- merge(AllPondBarChart, SE)

AllPondBarChart$Date <- as.Date(AllPondBarChart$Date , format = "%d-%b-%y")
AllPondBarChart$Date <- gsub("2023-", "", AllPondBarChart$Date)
```

```{r}
# Assuming your dataset has 'Biomass_SD' for the standard deviation
ggplot(AllPondBarChart, aes(x = `Date`, y = Biomass, fill = Type)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin = Biomass - se, ymax = Biomass + se),
                position = position_dodge(width = 0.9),
                width = 0.25) + # Width of the error bars
  labs(x = "Date 2023", y = "Biomass (mg)", title = "Avg. subsidy export of sampled ponds without dragonflies (1,3,5,6,8,9,12)") +
  scale_fill_manual(values = c("NoNemoDry" = "red", "NemoDry" = "blue"),
                    labels = c("N. hostilis", "Other insects")) +
  ylim(0,500) +
  theme_minimal()

```















































































```{r}
ggplot(AllPondBarChart, aes(x = `Date`, y = Biomass, fill = Type)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Date 2022", y = "Biomass (mg)", title = "Average subsidy export of 7 sampled ponds in 2022 (1,3,5,6,8,9,12)") +
  scale_fill_manual(values = c("NoNemoDry" = "red", "NemoDry" = "blue"),
                    labels = c("N. hostilis", "Other insects")) +
  ylim(0,500)+
  theme_minimal()
```

```{r}

AllPonds23 <- subset(floating2023, Pond %in% c("1", "3", "5", "6","12","8","9"))

AllPonds23Nemo <- subset(AllPonds23, ID %in% c("Nemo"))
AllPonds23Other <- subset(AllPonds23, ID %in% c("Other"))


AllPonds23NemoDate <- aggregate(AllPonds23Nemo$Total_SampleDW ~ AllPonds23Nemo$Date, data = AllPonds23Nemo, FUN = mean)


AllPonds23OtherDate <- aggregate(AllPonds23Other$Total_SampleDW ~ AllPonds23Other$Date, data = AllPonds23Other, FUN = mean)

#need to rename col for succesful merge 
names(AllPonds23NemoDate)[names(AllPonds23NemoDate) == 'AllPonds23Nemo$Date'] <- 'Date'
names(AllPonds23OtherDate)[names(AllPonds23OtherDate) == 'AllPonds23Other$Date'] <- 'Date'

AllPondBarChart23 <- left_join(AllPonds23NemoDate, AllPonds23OtherDate, by = "Date")

names(AllPondBarChart23)[names(AllPondBarChart23) == 'AllPonds23Nemo$Total_SampleDW'] <- 'NemoDry'

names(AllPondBarChart23)[names(AllPondBarChart23) == 'AllPonds23Other$Total_SampleDW'] <- 'NoNemoDry'
```

```{r}
AllPondBarChart23 <- AllPondBarChart23 %>%
  pivot_longer(cols = c(NoNemoDry, NemoDry),
               names_to = "Type",
               values_to = "Biomass")

AllPondBarChart23$Date <- as.Date(AllPondBarChart23$Date , format = "%d-%b-%y")
AllPondBarChart23$Date <- gsub("2023-", "", AllPondBarChart23$Date)
```

```{r}
ggplot(AllPondBarChart23, aes(x = `Date`, y = Biomass, fill = Type)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Date 2023", y = "Biomass (mg)", title = "Average subsidy export of 7 sampled ponds in 2023 (1,3,5,6,8,9,12)") +
  scale_fill_manual(values = c("NoNemoDry" = "red", "NemoDry" = "blue"),
                    labels = c("N. hostilis", "Other insects")) +
   ylim(0,500)+
  theme_minimal()
```