---
title: "DataSheet"
author: "Parker Bausman"
date: "2024-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

## Preparing data for modeling :) 

Steps 
take nemo and all other sheets
group by date, pond, sample, direction 


```{r}
Float1 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/FLOAT23-MB.csv", header=TRUE)
Float2 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/FLOAT23-PB.csv", header=TRUE)
```



```{r}
#combine data 
Float <- rbind(subsetFloat,subsetFloat2022)
```


```{r}
#read in LW data 
lw<-read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/LW-Float.csv",header=TRUE)
head(lw)
```


```{r}
#merge float data and LW data 
Float <- merge(Float, lw, by="ID", all=T)
```

```{r}
# calculating log (dry weight) from length
Float$logDW <- with(Float, a + (b * log((Length), base=base)))

#untransforming log (dry weight) to dry weight (mg)
Float$DW <- with(Float, (base^(logDW)))
```

```{r}
#now multiply dry weight by number of individuals 
Float$SampleDW <- NA

Float$SampleDW <- (Float$DW * Float$Count)
```

```{r}
#Pair down to cols needed 
Float <- Float[, c(1,2,3,4,5,14)]
```

```{r}
#Separate by nemo or no nemo 
FloatNemo <- subset(Float, ID %in% c("hostilis"))
FloatOther <- subset(Float, ID %in% c("Antisoptera", "Zygoptera", "nigriculus",  "Midges","Ceratopogonidae","Diptera", "Mosquito", "externus"))
```

```{r}
#summarize by sample
FloatNemo <- FloatNemo %>%
  group_by( Date, Pond, Direction) %>%
  summarize(Total_SampleDW = sum(SampleDW))
```
```{r}
#summarize by sample
FloatOther <- FloatOther %>%
  group_by( Date, Pond, Direction) %>%
  summarize(Total_SampleDW = sum(SampleDW))
```


```{r}
#add nemo non nemo col to each
FloatNemo$ID <- "Nemo"
FloatOther$ID <- "Other"

```

```{r}
FloatAll <- rbind(FloatNemo, FloatOther)

FloatAll$Date <- as.factor(FloatAll$Date)
```


```{r}
#now separate 2022 and 2023 to see if different 
floating2023 <- FloatAll[!grepl("22", FloatAll$Date), ]
floating2022 <- FloatAll[!grepl("23", FloatAll$Date), ]
```

```{r}
floating2022$Pond <- gsub("MC Pond ", "", floating2022$Pond)
floating2023$Pond <- gsub("MC Pond ", "", floating2023$Pond)
floating2022$Pond <- gsub("c", "", floating2022$Pond)
floating2023$Pond <- gsub("c Pond ", "", floating2023$Pond)
floating2022$Pond <- gsub("a", "", floating2022$Pond)
floating2023$Pond <- gsub("a Pond ", "", floating2023$Pond)
floating2022$Pond <- gsub("b", "", floating2022$Pond)
floating2023$Pond <- gsub("b Pond ", "", floating2023$Pond)
```


##### MAKE ONE WITH NO DRAGONFLIES FOR REAL 

```{r}
#Separate by nemo or no nemo 
NDFloatNemo <- subset(Float, ID %in% c("hostilis"))
#removed antisoptera
NDFloatOther <- subset(Float, ID %in% c( "Zygoptera", "nigriculus",  "Midges","Ceratopogonidae","Diptera", "Mosquito", "externus"))
```

```{r}
#summarize by sample
NDFloatNemo <- NDFloatNemo %>%
  group_by( Date, Pond, Direction) %>%
  summarize(Total_SampleDW = sum(SampleDW))
```
```{r}
#summarize by sample
NDFloatOther <- NDFloatOther %>%
  group_by( Date, Pond) %>%
  summarize(Total_SampleDW = sum(SampleDW))
```

```{r}
#add nemo non nemo col to each
NDFloatNemo$ID <- "Nemo"
NDFloatOther$ID <- "Other"

```

```{r}
NDFloatAll <- rbind(NDFloatNemo, NDFloatOther)

NDFloatAll$Date <- as.factor(NDFloatAll$Date)
```


```{r}
#now separate 2022 and 2023 to see if different 
NDfloating2023 <- FloatAll[!grepl("22", FloatAll$Date), ]
NDfloating2022 <- FloatAll[!grepl("23", FloatAll$Date), ]
```

#need to remove (MC POND)

```{r}
NDfloating2022$Pond <- gsub("MC Pond ", "", NDfloating2022$Pond)
NDfloating2023$Pond <- gsub("MC Pond ", "", NDfloating2023$Pond)
NDfloating2022$Pond <- gsub("c", "", NDfloating2022$Pond)
NDfloating2023$Pond <- gsub("c Pond ", "", NDfloating2023$Pond)
NDfloating2022$Pond <- gsub("a", "", NDfloating2022$Pond)
NDfloating2023$Pond <- gsub("a Pond ", "", NDfloating2023$Pond)
NDfloating2022$Pond <- gsub("b", "", NDfloating2022$Pond)
NDfloating2023$Pond <- gsub("b Pond ", "", NDfloating2023$Pond)
```

#MAKE SURE TO USE THIS WHEN GRAPHING 

