---
title: "Float_Combine"
author: "Parker Bausman"
date: "2024-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
```


```{r}
Float1 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/FLOAT23-MB.csv", header=TRUE)
Float2 <- read.csv("C:/Users/Parke/OneDrive/Documents/MS Thesis/Data/FLOAT23-PB.csv", header=TRUE)
```

```{r}
#float 1 has interspersed 2022 data, this code removes these rows 
Float1.1 <- Float1[!grepl("2022", Float1$Date), ]
Float1.1 <- as.data.frame(Float1.1)
Float2.1 <- Float2[!grepl("2022", Float2$Date), ]
Float2.1 <- as.data.frame(Float2.1)
```

```{r}
#make sure rows are the same so that rbind can work to combine datasets 
Float1.2 <- Float1.1[ ,c(1:3, 9, 12)]
Float2.2 <- Float2.1[ ,c(1:3, 9, 12)]
```

```{r}
#Rename Col ID on float1.2
Float1.2 <- Float1.2 %>%
  rename(ID = X.2)
```

```{r}
#Float 1 needs to have ponds renamed to just number not MC POND X
```


```{r}
#combine data 
Float2023 <- rbind(Float1.2,Float2.2)
```

```{r}
#to add average lenghts I need to make a new column
Float2023$Length <- NA
```

```{r}
# ugly for loop to attach lengths (changed from micro to millimeter )
for (i in 1:nrow(Float2023)) {
  # Check which pond 
  if (Float2023$ID[i] == "Antisoptera") {
    # If ID is antisoptera, add length
    #units is um 
    Float2023$Length [i] <- 70.000
  } else if (Float2023$ID[i] == "nigriculus") {
    # etc..
     Float2023$Length [i] <- 14.1212222222222
     
  } else if (Float2023$ID[i] == "hostilis") {
    # etc..
     Float2023$Length [i] <- 19.8364583333333
     
  } else if (Float2023$ID[i] == "Midges") {
    # etc..
     Float2023$Length [i] <- 3.45853
     
  } else if (Float2023$ID[i] == "Ceratopogonidae") {
    # etc..
     Float2023$Length [i] <- 2.131
     
  } else if (Float2023$ID[i] == "Diptera") {
    # etc..
     Float2023$Length [i] <- 3.000
     
  } else if (Float2023$ID[i] == "Mosquito") {
    # etc..
     Float2023$Length [i] <- 5.8935
     
  }
}
```

```{r}
subsetFloat <- subset(Float2023, ID %in% c("Antisoptera","nigriculus", "hostilis", "Midges","Ceratopogonidae","Diptera", "Mosquito", "Zygoptera"))
```



