---
title: "R Notebook"
output: html_notebook
---


```{r}
AllPonds22 <- subset(floating2023, Pond %in% c("1", "3", "5", "6","12","8","9"))

AllPonds22Nemo <- subset(AllPonds22, ID %in% c("Nemo"))
AllPonds22Other <- subset(AllPonds22, ID %in% c("Other"))


AllPonds22NemoID <- aggregate(AllPonds22Nemo$Total_SampleDW ~ AllPonds22Nemo$ID, data = AllPonds22Nemo, FUN = mean)


AllPonds22OtherID <- aggregate(AllPonds22Other$Total_SampleDW ~ AllPonds22Other$ID, data = AllPonds22Other, FUN = mean)

#need to rename col for succesful merge 
names(AllPonds22NemoID)[names(AllPonds22NemoID) == 'AllPonds22Nemo$ID'] <- 'ID'
names(AllPonds22OtherID)[names(AllPonds22OtherID) == 'AllPonds22Other$ID'] <- 'ID'

names(AllPonds22NemoID)[names(AllPonds22NemoID) == 'AllPonds22Nemo$Total_SampleDW'] <- 'AvgSampleDW'

names(AllPonds22OtherID)[names(AllPonds22OtherID) == 'AllPonds22Other$Total_SampleDW'] <- 'AvgSampleDW'

AllPondBarChart <- rbind(AllPonds22OtherID, AllPonds22NemoID)


```

```{r}
# Calculate the mean, standard deviation, and count for each ID
mean_sd_count22Nemo <- aggregate(Total_SampleDW ~ ID, data = AllPonds22Nemo, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Nemo <- do.call(data.frame, mean_sd_count22Nemo)
mean_sd_count22Nemo$mean <- mean_sd_count22Nemo$Total_SampleDW[, "mean"]
mean_sd_count22Nemo$sd <- mean_sd_count22Nemo$Total_SampleDW[, "sd"]
mean_sd_count22Nemo$n <- mean_sd_count22Nemo$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Nemo$se <- mean_sd_count22Nemo$Total_SampleDW.sd / sqrt(mean_sd_count22Nemo$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Nemo)[names(mean_sd_count22Nemo) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Nemo <- mean_sd_count22Nemo[, c("ID", "mean", "se")]
mean_sd_count22Nemo$Type <- "NemoDry"


#GET SE FOR OTHER TOO 
# Calculate the mean, standard deviation, and count for each ID
mean_sd_count22Other <- aggregate(Total_SampleDW ~ ID, data = AllPonds22Other, 
                           FUN = function(x) c(mean = mean(x), sd = sd(x), n = length(x)))

# Convert the resulting list into a data frame
mean_sd_count22Other <- do.call(data.frame, mean_sd_count22Other)
mean_sd_count22Other$mean <- mean_sd_count22Other$Total_SampleDW[, "mean"]
mean_sd_count22Other$sd <- mean_sd_count22Other$Total_SampleDW[, "sd"]
mean_sd_count22Other$n <- mean_sd_count22Other$Total_SampleDW[, "n"]

# Calculate the standard error
mean_sd_count22Other$se <- mean_sd_count22Other$Total_SampleDW.sd / sqrt(mean_sd_count22Other$Total_SampleDW.n)

#match format to other DF
names(mean_sd_count22Other)[names(mean_sd_count22Other) == 'Total_SampleDW.mean'] <- 'mean'
mean_sd_count22Other <- mean_sd_count22Other[, c("ID", "mean", "se")]
mean_sd_count22Other$Type <- "NoNemoDry"

```

```{r}
SE <- rbind(mean_sd_count22Other, mean_sd_count22Nemo )


AllPondBarChart <- merge(AllPondBarChart, SE)

AllPondBarChart <- AllPondBarChart[,-c(3,5)]
```

```{r}
# Assuming your dataset has 'Biomass_SD' for the standard deviation
ggplot(AllPondBarChart, aes(x = `ID`, y = mean, fill = ID)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se),
                position = position_dodge(width = 0.9),
                width = 0.25) +  # Width of the error bars
  labs(x = "Identity", y = "Biomass (mg)", 
       title = "Average subsidy export of N. hostilis and all other emergent insects (2023)",
       fill = "Insect Type") +  # Set legend title
  scale_fill_manual(values = c("Nemo" = "red", "Other" = "blue"), 
                    labels = c("Nemo" = "N. hostilis", "Other" = "Other")) +
  coord_cartesian(ylim = c(0, 225)) +  # Use coord_cartesian to set limits
  theme_minimal()
```

